# Generated by Django 5.0.7 on 2024-08-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_userdrawink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdrawink',
            name='last_claim_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
