# Generated by Django 5.0.7 on 2024-08-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_userdrawink_last_claim_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdrawink',
            name='last_claim_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
